/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2020-08-31 19:33:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch14shop.shoppping;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ch14.bookshop.shopping.CartDataBean;
import ch14.bookshop.shopping.CartDBBean;
import java.util.List;
import java.text.NumberFormat;

public final class cartList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/ch14shop/shoppping/../etc/color.jspf", Long.valueOf(1598449217976L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ch14.bookshop.shopping.CartDataBean");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("ch14.bookshop.shopping.CartDBBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
  String bodyback_c="#e0ffff";
  String back_c="#8fbc8f";
  String title_c="#5f9ea0";
  String value_c="#b0e0e6";
  String bar="#778899";

      out.write("\r\n");
      out.write("\r\n");

 String book_kind = request.getParameter("book_kind");
 String buyer = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Book Shopping Mall</title>\r\n");
      out.write("<link href=\"../etc/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"");
      out.print(bodyback_c);
      out.write("\">\r\n");

List<CartDataBean> cartLists = null;
CartDataBean cartList = null;
int count = 0;
int number = 0;
int total = 0;

if(session.getAttribute("id")==null){
   response.sendRedirect("shopMain.jsp");        
}else{
   CartDBBean bookProcess = CartDBBean.getInstance();
   count = bookProcess.getListCount(buyer);

   if(count == 0){

      out.write("\r\n");
      out.write("   <h3><b>장바구니</b></h3>\r\n");
      out.write("   <table> \r\n");
      out.write("     <tr><td >장바구니에 담긴 물품이 없습니다.</td> </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("     <input type=\"button\" value=\"쇼핑계속\" \r\n");
      out.write("     onclick=\"javascript:window.location='list.jsp?book_kind=");
      out.print(book_kind);
      out.write("'\">\r\n");

   }else{
     cartLists = bookProcess.getCart(buyer);
 
      out.write("\r\n");
      out.write("   <h3><b>장바구니</b></h3>\r\n");
      out.write("   <form name=\"cartform\">\r\n");
      out.write("   <table> \r\n");
      out.write("     <tr> \r\n");
      out.write("       <td width=\"50\">번호</td> \r\n");
      out.write("       <td width=\"300\">책이름</td> \r\n");
      out.write("       <td width=\"100\">판매가격</td>\r\n");
      out.write("       <td width=\"150\">수량</td> \r\n");
      out.write("       <td width=\"150\">금액</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      \r\n");

   for(int i=0;i<cartLists.size();i++){
     cartList = (CartDataBean)cartLists.get(i);

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     <tr> \r\n");
      out.write("       <td width=\"50\">");
      out.print(++number );
      out.write("</td> \r\n");
      out.write("       <td  width=\"300\" align=\"left\">\r\n");
      out.write("         <img src=\"../../imageFile/");
      out.print(cartList.getBook_image());
      out.write("\" \r\n");
      out.write("             border=\"0\" width=\"30\" height=\"50\" align=\"middle\">\r\n");
      out.write("             ");
      out.print(cartList.getBook_title());
      out.write("\r\n");
      out.write("       </td> \r\n");
      out.write("       <td width=\"100\">");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_price()));
      out.write("</td>\r\n");
      out.write("       <td width=\"150\">\r\n");
      out.write("          <input type=\"text\" name=\"buy_count\" size=\"5\" value=\"");
      out.print(cartList.getBuy_count());
      out.write("\">\r\n");
      out.write("          ");
 
          String url = "updateCartForm.jsp?cart_id="+cartList.getCart_id()+
            "&book_kind="+book_kind + "&buy_count="+cartList.getBuy_count();
          
          
      out.write("\r\n");
      out.write("          <input type=\"button\" value=\"수정\"\r\n");
      out.write("            onclick=\"javascript:window.location='");
      out.print(url);
      out.write("'\">\r\n");
      out.write("       </td> \r\n");
      out.write("       <td align=\"center\"  width=\"150\">\r\n");
      out.write("          ");
total += cartList.getBuy_count()*cartList.getBuy_price();
      out.write("\r\n");
      out.write("            ");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_count()*cartList.getBuy_price()) );
      out.write("\r\n");
      out.write("          <input type=\"button\" value=\"삭제\" \r\n");
      out.write("            onclick=\"javascript:window.location=\r\n");
      out.write("            'cartListDel.jsp?list=");
      out.print(cartList.getCart_id());
      out.write("&book_kind=");
      out.print(book_kind);
      out.write("'\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
}
      out.write("\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td colspan=\"5\" align=\"right\"><b>총 금액 : ");
      out.print(NumberFormat.getInstance().format(total));
      out.write("</b></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td colspan=\"5\">\r\n");
      out.write("         <input type=\"button\" value=\"구매하기\" \r\n");
      out.write("            onclick=\"javascript:window.location='buyForm.jsp'\">\r\n");
      out.write("         <input type=\"button\" value=\"쇼핑계속\" \r\n");
      out.write("            onclick=\"javascript:window.location='list.jsp?book_kind=");
      out.print(book_kind);
      out.write("'\">\r\n");
      out.write("         <input type=\"button\" value=\"장바구니비우기\" \r\n");
      out.write("            onclick=\"javascript:window.location='cartListDel.jsp?list=all&book_kind=");
      out.print(book_kind);
      out.write("'\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   </form>\r\n");

  } 
}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
