/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2020-08-22 20:56:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch13;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ch13.board.BoardDataBean;
import ch13.board.BoardDBBean;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/ch13/color.jspf", Long.valueOf(1598111902189L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ch13.board.BoardDBBean");
    _jspx_imports_classes.add("ch13.board.BoardDataBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

   String bodyback_c="#FFF0B5";
   String value_c="#FFE271";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"");
      out.print(bodyback_c );
      out.write("\">\r\n");
      out.write("\t");

		int num=Integer.parseInt(request.getParameter("num"));
		String pageNum=request.getParameter("pageNum");
		try{
			BoardDBBean dbPro=BoardDBBean.getInstance();
			BoardDataBean article=dbPro.updateGetArticle(num);	

	
      out.write("\r\n");
      out.write("\t<p>글수정</p>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form method=\"post\" name=\"writeform\"\r\n");
      out.write("\t\taction=\"updatePro.jsp?pageNum=");
      out.print(pageNum );
      out.write("\" onsubmit=\"return writeSave()\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">이름</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"330\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=\"10\" maxlength=\"10\" name=\"writer\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(article.getWriter() );
      out.write("\" style=\"ime-mode:active;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"num\" value=\"");
      out.print(article.getNum() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">제목</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"330\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=\"40\" maxlength=\"50\" name=\"subject\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(article.getSubject() );
      out.write("\" style=\"ime-mode:active;\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">Email</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"330\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" size=\"40\" maxlength=\"30\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(article.getEmail() );
      out.write("\" style=\"ime-mode:inactive;\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">내 용</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"330\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"content\" rows=\"13\" cols=\"40\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"ime-mode:active;\">");
      out.print(article.getContent() );
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">비밀번호</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" width=\"330\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" size=\"8\" maxlength=\"12\"\r\n");
      out.write("\t\t\t\t\t\tname=\"passwd\" style=\"ime-mode:inactive;\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=2 bgcolor=\"");
      out.print(value_c );
      out.write("\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"글수정\">\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"목록보기\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"document.location.href='list.jsp?pageNum=");
      out.print(pageNum );
      out.write("'\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");

		}catch(Exception e){}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
